"""Local pretrained-language feasibility only; no architecture/learning claim."""
from pathlib import Path
import argparse,json,time,hashlib,subprocess,resource,importlib.metadata
import torch
from transformers import AutoTokenizer,AutoModelForCausalLM

def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
    p=argparse.ArgumentParser();p.add_argument('--model',type=Path,required=True);p.add_argument('--transformers-repo',type=Path,required=True);p.add_argument('--out',type=Path,required=True);a=p.parse_args();torch.set_num_threads(1);torch.manual_seed(1531);source=json.loads((a.model/'source_identity.json').read_text());assert sha(a.model/'model.safetensors')==source['weights_sha256'];head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=a.transformers_repo,text=True).strip();assert head=='052e652d6d53c2b26ffde87e039b723949a53493'
    start=time.perf_counter();tokenizer=AutoTokenizer.from_pretrained(a.model,local_files_only=True,trust_remote_code=False);model=AutoModelForCausalLM.from_pretrained(a.model,local_files_only=True,trust_remote_code=False,torch_dtype=torch.float32,attn_implementation='eager').eval().requires_grad_(False);load_seconds=time.perf_counter()-start
    prompts=['The key moved from the red box to the blue box. Which box now holds the key? Answer only with the color.','The key moved from the blue box to the red box. Which box now holds the key? Answer only with the color.'];rows=[];last_logits=[];token_lists=[];cache_bytes=[]
    with torch.no_grad():
        for prompt in prompts:
            text=tokenizer.apply_chat_template([dict(role='user',content=prompt)],tokenize=False,add_generation_prompt=True);inputs=tokenizer(text,return_tensors='pt');token_lists.append(inputs['input_ids'][0].tolist());start=time.perf_counter();out=model(**inputs,use_cache=True);seconds=time.perf_counter()-start;assert torch.isfinite(out.logits).all();last_logits.append(out.logits[:,-1].clone());cache=out.past_key_values.to_legacy_cache() if hasattr(out.past_key_values,'to_legacy_cache') else out.past_key_values;cache_bytes.append(sum(t.numel()*t.element_size() for layer in cache for t in layer));start=time.perf_counter();generated=model.generate(**inputs,max_new_tokens=8,do_sample=False,temperature=None,top_p=None,top_k=None,pad_token_id=tokenizer.eos_token_id);decoded=tokenizer.decode(generated[0,inputs['input_ids'].shape[1]:],skip_special_tokens=True);rows.append(dict(prompt=prompt,input_tokens=inputs['input_ids'].shape[1],prefill_seconds=seconds,generation_seconds=time.perf_counter()-start,new_tokens=generated.shape[1]-inputs['input_ids'].shape[1],output=decoded))
    assert sorted(token_lists[0])==sorted(token_lists[1]);assert not torch.equal(last_logits[0],last_logits[1]);assert model.lm_head.weight.data_ptr()==model.model.embed_tokens.weight.data_ptr();a.out.mkdir(parents=True,exist_ok=True)
    result=dict(status='CPU_PREFLIGHT_ONLY_NO_CONTINUAL_LEARNING_RESULT',model_source=source,transformers_commit=head,versions={m:importlib.metadata.version(m) for m in ['torch','numpy','transformers','tokenizers','safetensors','huggingface-hub']},device='cpu',dtype='float32',attention_implementation='eager',torch_threads=1,load_seconds=load_seconds,parameters=sum(p.numel() for p in model.parameters()),parameter_bytes=sum(p.numel()*p.element_size() for p in model.parameters()),tied_embeddings_verified=True,cache_bytes=cache_bytes,token_multisets_equal=True,order_changes_logits=True,order_logit_difference_l2=float((last_logits[0]-last_logits[1]).norm()),queries=rows,max_process_rss_bytes=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024,script_sha256=sha(__file__),scope='Two feasibility prompts only; pretrained responses are not learned persistent memory, general reasoning verification or a new architecture result. GPU fit, adaptation and long-horizon behavior remain unmeasured.')
    (a.out/'preflight.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
